FROM mysql:8.4
# Configuracion del proyecto
COPY docker/mysql/my.cnf /etc/mysql/conf.d/my.cnf
# Permisos
RUN chmod 0644 /etc/mysql/conf.d/my.cnf
# Instalacion y limpieza
RUN microdnf install -y tzdata && microdnf clean all
# Zona horaria
ENV TZ=America/La_Paz