<?php
/**
 * Microservicio "Produccion y Cocina"
 */

return [
    'host' => env('RABBITMQ_HOST', '127.0.0.1'),
    'port' => (int) env('RABBITMQ_PORT', 5672),
    'user' => env('RABBITMQ_USER', 'guest'),
    'password' => env('RABBITMQ_PASSWORD', 'guest'),
    'vhost' => env('RABBITMQ_VHOST', '/'),
    'exchange' => env('RABBITMQ_EXCHANGE', 'outbox.events'),
    'exchange_type' => env('RABBITMQ_EXCHANGE_TYPE', 'fanout'),
    'exchange_durable' => (bool) env('RABBITMQ_EXCHANGE_DURABLE', true),
    'routing_key' => env('RABBITMQ_ROUTING_KEY', ''),
    'queue' => env('RABBITMQ_QUEUE', ''),
    'queue_durable' => (bool) env('RABBITMQ_QUEUE_DURABLE', true),
    'queue_exclusive' => (bool) env('RABBITMQ_QUEUE_EXCLUSIVE', false),
    'queue_auto_delete' => (bool) env('RABBITMQ_QUEUE_AUTO_DELETE', false),
    'binding_key' => env('RABBITMQ_BINDING_KEY', ''),
    'publish_retries' => (int) env('RABBITMQ_PUBLISH_RETRIES', 3),
    'publish_backoff_ms' => (int) env('RABBITMQ_PUBLISH_BACKOFF_MS', 250),
    'connect_timeout' => (int) env('RABBITMQ_CONNECT_TIMEOUT', 3),
    'read_write_timeout' => (int) env('RABBITMQ_READ_WRITE_TIMEOUT', 3),
    'inbound' => [
        'exchange' => env('INBOUND_RABBITMQ_EXCHANGE', ''),
        'queue' => env('INBOUND_RABBITMQ_QUEUE', ''),
        'routing_keys' => env('INBOUND_RABBITMQ_ROUTING_KEYS', ''),
        'schema_versions' => env('INBOUND_SCHEMA_VERSIONS', '1'),
        'max_retries' => (int) env('INBOUND_RABBITMQ_MAX_RETRIES', 3),
        'dlx' => env('INBOUND_RABBITMQ_DLX', ''),
        'dlq' => env('INBOUND_RABBITMQ_DLQ', ''),
        'dlq_routing_key' => env('INBOUND_RABBITMQ_DLQ_ROUTING_KEY', ''),
        'retry_exchange' => env('INBOUND_RABBITMQ_RETRY_EXCHANGE', ''),
        'retry_queue' => env('INBOUND_RABBITMQ_RETRY_QUEUE', ''),
        'retry_routing_key' => env('INBOUND_RABBITMQ_RETRY_ROUTING_KEY', ''),
        'retry_delays' => env('INBOUND_RABBITMQ_RETRY_DELAYS', '10,60,300'),
    ],
    'event_queues' => [
        \App\Domain\Produccion\Events\ProductoCreado::class => 'produccion.producto-creado',
        \App\Domain\Produccion\Events\ProductoActualizado::class => 'produccion.producto-actualizado',
        \App\Domain\Produccion\Events\RecetaVersionCreada::class => 'produccion.receta-creada',
        \App\Domain\Produccion\Events\RecetaVersionActualizada::class => 'produccion.receta-actualizada',
        \App\Domain\Produccion\Events\DireccionCreada::class => 'produccion.direccion-creada',
        \App\Domain\Produccion\Events\DireccionActualizada::class => 'produccion.direccion-actualizada',
        \App\Domain\Produccion\Events\PacienteCreado::class => 'produccion.paciente-creado',
        \App\Domain\Produccion\Events\PacienteActualizado::class => 'produccion.paciente-actualizado',
        \App\Domain\Produccion\Events\SuscripcionCreada::class => 'produccion.suscripcion-creada',
        \App\Domain\Produccion\Events\SuscripcionActualizada::class => 'produccion.suscripcion-actualizada',
        \App\Domain\Produccion\Events\PaqueteCreado::class => 'produccion.paquete-creado',
        \App\Domain\Produccion\Events\PaqueteActualizado::class => 'produccion.paquete-actualizado',
        \App\Domain\Produccion\Events\PaqueteParaDespachoCreado::class => 'produccion.paquete-despacho-creado',
        \App\Domain\Produccion\Events\CalendarioCreado::class => 'produccion.calendario-creado',
        \App\Domain\Produccion\Events\CalendarioActualizado::class => 'produccion.calendario-actualizado',
        \App\Domain\Produccion\Events\CalendarioItemCreado::class => 'produccion.calendario-item-creado',
        \App\Domain\Produccion\Events\CalendarioItemActualizado::class => 'produccion.calendario-item-actualizado',
        \App\Domain\Produccion\Events\OrdenProduccionCreada::class => 'produccion.orden-creada',
        \App\Domain\Produccion\Events\OrdenProduccionPlanificada::class => 'produccion.orden-planificada',
        \App\Domain\Produccion\Events\OrdenProduccionProcesada::class => 'produccion.orden-procesada',
        \App\Domain\Produccion\Events\OrdenProduccionCerrada::class => 'produccion.orden-cerrada',
        \App\Domain\Produccion\Events\OrdenProduccionDespachada::class => 'produccion.orden-despachada',
        \App\Domain\Produccion\Events\ProduccionBatchCreado::class => 'produccion.batch-orden-creado',
    ],
];
